### ISSUE TITLE
Починить тесты и настроить CI

### ISSUE THREAD

**Issue by kugaevsky** [NNRUG/it52-rails#117]
1. Удалить ненужные уже тесты.
2. Поправить актуальные тесты.
3. Настроить корректную работу Travis CI.

**Comment by vittorius** [comment]
Привет. Могу взяться за этот issue?

**Comment by kugaevsky** [comment]
@vittorius да, приассайни себя к нему.

**Comment by vittorius** [comment]
Не могу...

**Comment by vittorius** [comment]
Думаю, тебе нужно сделать меня collaborator-ом. Или самому меня заассайнить.

**Comment by noroot** [comment]
@vittorius @kugaevsky ага только мемберы ассайнится могут, пусть просто забирает, привет

**Comment by kugaevsky** [comment]
@vittorius Добавил в коллабораторы

**Comment by harrykiselev** [comment]
Парни, я уже сделал эту таску :)
Молчал, так как тоже не могу заассайнить на себя и думал что никто не возьмется :)

**Comment by harrykiselev** [comment]
@vittorius ты много работы по этой ишьюхе сделал? :)

**Comment by vittorius** [comment]
Нет, не начинал ))) выходные последние тёплые )) ок.

**Comment by kugaevsky** [comment]
Fixed with #119
