### ISSUE TITLE
Генерация аваторов из Google+

### ISSUE THREAD

**Issue by ehles** [NNRUG/it52-rails#15]
Авторизовался через G+, там у меня аватар в gif, на сайте же отображается будто скриншот из плеера, с кнопкой "play" на носу: ![ScreenShot](http://goo.gl/mR4XNW)

**Comment by kugaevsky** [comment]
Мы гуглу на слово верим. Отдаёт с кнопокой — рисуем с кнопкой.

**Comment by r3nya** [comment]
@ehles @kugaevsky странно, но на s3 он в jpg пришел.

**Comment by kugaevsky** [comment]
Есесно. Мы в jpg у себя преобразуем. Но исходник картинки ровно тот, что гугл отдаёт.

**Comment by ehles** [comment]
Гугл должен был вернуть что-то вроде этого:

``` json
{
 "id": "109206309251350142397",
 "name": "Denis Deryabin",
 "given_name": "Denis",
 "family_name": "Deryabin",
 "link": "https://plus.google.com/109206309251350142397",
 "picture": "https://lh4.googleusercontent.com/-qvZgLQrY4dc/AAAAAAAAAAI/AAAAAAAAB4k/BCsnxqsgQ_E/photo.jpg",
 "gender": "male",
 "locale": "ru"
}
```

Если открыть ссылку на picture, тот там вместо jpg - gif:
![picture](https://lh4.googleusercontent.com/-qvZgLQrY4dc/AAAAAAAAAAI/AAAAAAAAB4k/BCsnxqsgQ_E/photo.jpg)

**Comment by ehles** [comment]
нашел в чем причина, вы используете параметр "?sz=" чтобы гугл возвращал сразу квадратную картинку, он и делает её такой.
![пример использования sz=250](https://lh4.googleusercontent.com/-qvZgLQrY4dc/AAAAAAAAAAI/AAAAAAAAB4k/BCsnxqsgQ_E/photo.jpg?sz=250)
