### ISSUE TITLE
500 response when trying to login with VK oauth

### ISSUE THREAD

**Issue by AlexDobrushskiy** [NNRUG/it52-rails#16]
This one may be a duplicate of https://github.com/NNRUG/it52-rails/issues/11 .
Anyway, those issue was closed 16.09.2014, but today, 14.11.2014, VK auth still doesn't work.

There was 500 response on GET for http://www.it52.info/oauth/vkontakte/callback?code=44d4fae697d9293202&state=36afd378370c5dd8551b9d046de4b558773cfc8ce9669f82

Actually, opening those URL next time doesn't cause 500 error anymore. 

If some additional information needed - please let me know.

**Comment by kugaevsky** [comment]
Fixed
