### ISSUE TITLE
Subscribe to site updates

### ISSUE THREAD

**Issue by alex-petrenko** [NNRUG/it52-rails#17]
This is an absolutely crucial functionality which I could not find on the website. How do I get updates about the latest events?
E-mail newsletters should be implemented.

**Comment by kugaevsky** [comment]
You absolutely right. 
We are working on the project in the free time, so I will implement it when I have some.
As a fast solution I can turn on RSS feed with events stream later this week.

**Comment by kugaevsky** [comment]
@alex-petrenko here I fixed it for you http://www.it52.info/events.atom

**Comment by kugaevsky** [comment]
And iCalendar feed could be useful too http://www.it52.info/events.ics

**Comment by kugaevsky** [comment]
@alex-petrenko implemented. You can subscribe (or unsubscribe) to IT52 newsletter in [your profile](http://www.it52.info/my/profile/edit).
