### ISSUE TITLE
Не работает регистрация и сброс пароля

### ISSUE THREAD

**Issue by kromberg** [NNRUG/it52-rails#174]
pomidorka.kromberg@gmail.com - сбросил пароль - не приходит email
kromberged@gmail.com - зарегистрировался - не приходит код активации

**Comment by r3nya** [comment]
Привет! Спасибо за фидбек, постараемся пофиксить

**Comment by kugaevsky** [comment]
@kromberg Спасибо, что заметили. Починено в 20bc4a973e296afa3f6af49cc7336f54ce25f272.
