### ISSUE TITLE
Site field in profile can't be saved with empty value

### ISSUE THREAD

**Issue by noroot** [NNRUG/it52-rails#18]
Site field in profile can't be saved with empty value, but tells that it can

![](https://photos-5.dropbox.com/t/1/AAAFcuucdJvyYp6nbeFS0mq9rf_sfIK9CHz3l3Ff90n0Kw/12/531631/png/1024x768/3/1417104000/0/2/Screenshot%202014-11-27%2017.21.21.png/pkk3tF2NaoZOVP1Kx3ieB6NtJuLfbBDvcwiLoQ8aj1M)

**Comment by kugaevsky** [comment]
Fixed with @e471c38
