### ISSUE TITLE
Проблем с регистрацией

### ISSUE THREAD

**Issue by n0byk** [NNRUG/it52-rails#254]
Всем привет!
После регистрации не приходит письмо с конфирмом на почту (ВООБЩЕ НЕ ПРИХОДИТ).
еще проблемы с модулем Oauth - не работает....

**Comment by kugaevsky** [comment]
Привет, @n0byk 

Починили, уже должно быть всё хорошо.

**Comment by r3nya** [comment]
@n0byk проверить плиз

**Comment by kugaevsky** [comment]
Раз повторных жалоб нет, будем считать, что починилось.
