### ISSUE TITLE
Нет топика для дизайнеров(

### ISSUE THREAD

**Issue by polinamazaeva** [NNRUG/it52-rails#407]
Здравствуйте! Не знала, куда написать. Я UX/UI дизайнер (именно в таком порядке по предпочтению) и не нашла ветки для обсуждения общих тем с нижегородскими коллегами. Скажите, пожалуйста, такое планируется? Ведь, как показала практика, мы очень важное звено в разработке и без нас никак.

**Comment by r3nya** [comment]
Добрый день, @polinamazaeva!

Вы имеете ввиду какого-то локального чата по UX/UI? Я не слышал о таком еще

**Comment by polinamazaeva** [comment]
Да, я имею в виду, нет в списке специальной тематической группы (в рамках сообщества it52 - https://www.it52.info/communities), хотя роль UI/UX очень важна. Есть про информационную архитектуру, но, как оказалось, это не о том. Планируется ли такой чат?

**Comment by r3nya** [comment]
@polinamazaeva понял. Организация сообществ – дело добровольное. Обычно нужны какие-то инициаторы для этого, и всё. Вы вправе создать подобный чат, а мы сделаем пиар по нашим каналам/соц сетям

**Comment by polinamazaeva** [comment]
Поняла, спасибо)

**Comment by r3nya** [comment]
@polinamazaeva дайте знать если что, мы будем рады помочь :)
