### ISSUE TITLE
apipie-rails.git clone has failed

### ISSUE THREAD

**Issue by sam0var** [NNRUG/it52-rails#50]
When I run "vagrant provision" or "bundle install"(inside ssh) process stops with:

Fetching https://github.com/Apipie/apipie-rails.git
fatal: unable to access 'https://github.com/Apipie/apipie-rails.git/': Could not
 resolve host: github.com
Git error: command `git clone 'https://github.com/Apipie/apipie-rails.git'
"/home/vagrant/.rvm/gems/ruby-2.2.1@it52/cache/bundler/git/apipie-rails-9e3aad6d
a4aec0e24c846f80e4f637682f00cf62"
--bare --no-hardlinks --quiet` in directory /vagrant has failed.

System:
Windows 8.1
VirtualBox 4.3.12
Vagrant 1.6.3

What am i doing wrong?

**Comment by kugaevsky** [comment]
Does `$ git clone https://github.com/Apipie/apipie-rails.git` in box works good?

**Comment by sam0var** [comment]
No.
$ git clone https://github.com/Apipie/apipie-rails.git
Cloning into 'apipie-rails'...
fatal: unable to access 'https://github.com/Apipie/apipie-rails.git/': Could not resolve host: github.com

I try to update vagrant...

**Comment by kugaevsky** [comment]
Actually you can remove this line in `Gemfile` (this gem only generates API documentation)

    gem 'apipie-rails', git: 'https://github.com/Apipie/apipie-rails.git', ref: 'f697ec2a887cd73c00c846eceb2ce63a050ccb20'

and run `$ bundle install`

**Comment by sam0var** [comment]
It worked. But I got an error at the next step (run `$ bundle exec rake db:setup`):
```
rake aborted!
NameError: uninitialized constant Apipie
/vagrant/config/initializers/apipie.rb:1:in `<top (required)>'
```

**Comment by kugaevsky** [comment]
My bad.
Totally removed problem gem.
Just pull latest changed from repo.
