### ISSUE TITLE
Single Page Application, new desing and BEM [meet and discuss]

### ISSUE THREAD

**Issue by krll-k** [NNRUG/it52-rails#60]
Так было принято какое то решение по поводу использования или не использования SPA:
- Если да, то какое;
- Если нет, то давайте соберемся и определим?

Что на счет того чтобы взять и разработать новый дизайн заглавной страницы, есть дизайнеры?

Могу сверстать все согласно BEM, без bem-tools, вручную,
Я за то чтобы собраться и обсудить все это!!!

**Comment by r3nya** [comment]
Привет, @krll-k! 

Лично мне хотелось бы так:
- React
- ES6 + Babel

Я совсем не против BEM.

PS: cast @kugaevsky, @noroot, @sesm

**Comment by kugaevsky** [comment]
ES6 и Babel незаметно превращаются в coffeescript.

**Comment by kugaevsky** [comment]
Я против БЭМ. Эта чудная концепция мне не близка.
А вот переверстать на Foundation for apps с material design я только за.

**Comment by kugaevsky** [comment]
Продолжая разговор о SPA. Я совершенно не против намутить и на реакте, если всё будет без деградации относительно текущего функционала.

**Comment by r3nya** [comment]
@kugaevsky не будет деградации :wink:

**Comment by r3nya** [comment]
> ES6 и Babel незаметно превращаются в coffeescript.

@kugaevsky меня "надо сильно покусать", чтобы я начал писать на `coffeescript` ...

**Comment by krll-k** [comment]
@r3nya @kugaevsky я не против React, но очень уж хочется BEM. Не обязательно использовать их сборщики, вот посмотрите <a href="https://github.com/krll-k/vk.com">сюда</a>, сделано без всяких bem-tools и enb

Суть BEM не в том чтобы использовать их инструменты, можно разработать свои, но все разработчики Яндекс прошли весь этот путь, и у них это работает, правда порог вхождения не из низких, но что мешает создать самим упрощенную утилиту? Далее, BEM дает независимость блокам, тем кто не понимает что это такое и зачем нужно, вам <a href="http://bem.info">сюда</a>

Подведя итог, у кого когда будет свободный вечер чтобы встретить за кружкой и поговорить про предложенные мною изменения всерьез?

**Comment by kugaevsky** [comment]
@r3nya это можно устроить.
@krll-k я рад за разработчиков Яндекса и их сатанинские технологии, но вот от от таких классов в коде у меня кровь из глаз течёт.

```
class="link changelang__lang changelang__lang_ru"
```

И я всегд предпочту сделать

```
class="link changelang ru"
```

Перед тем как кого-нибудь хоть куда-то посылать неплохо поштудировать откуда у БЭМа [ноги растут](https://www.google.ru/search?q=oocss), а потом рассказать mdo и fat, что они всё неправильно сделали. Пацанам из ZURB тоже можно попробовать про БЭМ порассказывать.

После этого можно подводить итог.

PS А за кружкой я всегд готов обсудить. Давайте в пятницу в Капоне.

**Comment by sesm** [comment]
По поводу вёрстки:
Просто так переделывать вёрстку большого смысла, наверное, нет. Поводом переделать
вёрстку может быть новый дизайн, поэтому сначала можно рассмотреть идеи
для нового дизайна. 

По поводу SPA:
- Если всё-таки останавливаемся на React:
- Coffeescript или es6 - принципиальной разницы нет, React можно ипользовать и с
  тем и с тем.
- Деградации быть не должно, есть гем `react-rails` который позволит внедрять React постопенно рядом с существующим кодом, и даже (в теории) может делать рендеринг react кода на серверной стороне для поисковиков.

**Comment by r3nya** [comment]
> Что на счет того чтобы взять и разработать новый дизайн заглавной страницы, есть дизайнеры?

@krll-k дизайнеров пока нет

**Comment by kugaevsky** [comment]
@sesm всё верно говоришь. Только надо подумать только брать ли `react-rails` или всё-таки через `bower-rails` js-библиотеки добавлять. 
Деградация вполне возможна, так как API перестаёт быть read-only (если мы переписываем пусть постепенно, но **всё**), и та же работа с валидацией корректности форм ложится и на фронт, и на бэк.

**Comment by r3nya** [comment]
@kugaevsky в идеале `rails-api` + отдельный фронтенд, который компилится `gulp` и т.д.

**Comment by kugaevsky** [comment]
`rails-api` — это просто рельса без вьюшного куска стэка. Я был бы не против выкидывания и asset pipeline, если бы не одно «но». Хостинг у нас сейчас хероку (в видимо там и останется) и у меня нет познаний, каким образом собирать статику рельсоприложения в продакшне хероку без asset pipeline на gulp и ловко загружать её на AWS S3.
Есть ли они у вас?

**Comment by r3nya** [comment]
@kugaevsky я тоже не знаю … Но может быть google поможет? :smiley_cat:

**Comment by krll-k** [comment]
@r3nya а логотип уже есть?

О дизайне вообще не стоит переживать! Сперва необходимо подумать о бренде, прав ли я?

**Comment by kugaevsky** [comment]
@krll-k сперва нужно думать о людях.

**Comment by krll-k** [comment]
@kugaevsky может начать с постановки задач и целей перед сообществом?

**Comment by kugaevsky** [comment]
@krll-k дык карты в руки!

**Comment by krll-k** [comment]
@kugaevsky загуглил по ключевому слову "цели сообщества", и вышел на <a href="http://globe-forum.com/cel-i-zadachi-soobshhestva">это</a>, правда там пусто

Может юридически зарегистрироваться? Нужно ли это нам?

**Comment by kugaevsky** [comment]
@krll-k никаких членских взносов никогда здесь не будет.
Можешь погуглить по запросу «регистрация НКО». Узнаешь много нового.

**Comment by krll-k** [comment]
deleted text

**Comment by kugaevsky** [comment]
OMG, ну какая википедия. Закон почитай.

**Comment by r3nya** [comment]
@krll-k зачем нам это? Люди и без НКО могут встретиться и развлечься. Не?

**Comment by r3nya** [comment]
> а логотип уже есть?

Да, конечно. https://github.com/NNRUG/it52-rails/blob/it52/app/assets/images/logo-it52.png

**Comment by krll-k** [comment]
@r3nya @kugaevsky ок, но тогда все ровно мне кажется необходим хоть какой то документ- устав сообщества, пускай и не зарегистрированный в соответствующих органах

Но мне кажется вы все ровно упускаете из вида нечто главное, если зарегистрироваться юридически, то тогда и отношение будет совсем иным

**Comment by r3nya** [comment]
@krll-k да мы тут не масонскую ложу делаем в общем-то. Все и так понимают, что главное правило – не быть мудаком.

btw, ты куда-то далеко ушел от spa & bem …

**Comment by krll-k** [comment]
@r3nya да, регистрация вписывается в концепцию новый дизайна!

**Comment by krll-k** [comment]
Документ устав нужен?

**Comment by krll-k** [comment]
Рано или поздно вопрос этот должен был быть задан, зря пинаете меня

**Comment by r3nya** [comment]
@krll-k вспомнилось что-то :wink: 

```
Никому не рассказывать о бойцовском клубе.
Никогда никому не рассказывать о бойцовском клубе.
Если противник потерял сознание или делает вид, что потерял, или говорит «Хватит» — поединок окончен.
В схватке участвуют только двое.
Не более одного поединка за один раз.
Бойцы сражаются без обуви и голые по пояс.
Поединок продолжается столько, сколько потребуется.
Новичок обязан принять бой.
```

**Comment by krll-k** [comment]
Перед тем как создавать новый дизайн, который к слову должен думать о людях, может попробуем понять чем сообщество будет заниматься, мне например это не ясно. Мероприятия проводить?

**Comment by krll-k** [comment]
@r3nya ну за шаблон пойдет! Первые два правила точно можно позаимствовать!

**Comment by krll-k** [comment]
А вообще кто какие примеры знает IT- сообществ, в данном случаи региональных как IT52?

**Comment by krll-k** [comment]
Зачем я все это пишу, а где вообще об этом писать как не здесь?

**Comment by r3nya** [comment]
> А вообще кто какие примеры знает IT- сообществ, в данном случаи региональных как IT52?

http://it61.info/

> Зачем я все это пишу, а где вообще об этом писать как не здесь?

Use [telegram](https://telegram.me/joinchat/AfMU4ABHPrqm36kOMmuB2Q), Luke!

**Comment by r3nya** [comment]
> Зачем я все это пишу, а где вообще об этом писать как не здесь?

Use [telegram](https://telegram.me/joinchat/AfMU4ABHPrqm36kOMmuB2Q), Luke!

**Comment by krll-k** [comment]
@r3nya &#x1f610;

**Comment by krll-k** [comment]
<pre>
Мы не хотим устраивать мероприятия, мы хотим участвовать
Пусть лучше кто нибудь устроит его за нас
...
Мы хотим получать призы, писать код под кофе и печенки
</pre>

**Comment by r3nya** [comment]
@krll-k огонь!
![wow!](http://38.media.tumblr.com/897d30d377543ddad19b4660c46a57e0/tumblr_nou0jb0m1P1qz6sh9o1_500.gif)

**Comment by sesm** [comment]
@krll-k юр. лицо это очень много геморроя. А всё что сейчас делается можно делать без него. Когда юр. лицо для какой-то цели понадобится, то проще будет попросить знакомую организацию (работодателя или спонсора).

**Comment by kugaevsky** [comment]
Доделай календарь и запили каталог площадок для мероприятий, если хочешь
сделать что-нибудь полезное.
Прожекты о регистрации НКО и рисованию логотипов можно перенести в Google
Drive. Напиши устав, нарисуй логотип и присылай.

**Comment by sesm** [comment]
Новый дизайн уже сделан, SPA - вопрос спорный, а BEM и подавно.
@kugaevsky может быть закроем этот тикет? А тикеты про SPA и BEM если нужно создадут заново.

**Comment by kugaevsky** [comment]
@sesm 👍
