### ISSUE TITLE
New logo for it52

### ISSUE THREAD

**Issue by kugaevsky** [NNRUG/it52-rails#7]
We need the very new shiny logo for the great goodness!

**Comment by GnuriaN** [comment]
Дайте ссылку на лого в векторе =)

**Comment by kugaevsky** [comment]
@GnuriaN пожалуйста: https://www.dropbox.com/sh/k1k8ln6ljsrbai0/AACn9DLaianUNIVkA5Ao8OZba?dl=0

Не прошло и 2 года.
