### ISSUE TITLE
Едет вёрстка в заголовке.

### ISSUE THREAD

**Issue by sesm** [NNRUG/it52-rails#82]
Когда я залогинен и нажимаю на кнопку "О сайте", то некоторое время наблюдаю такую картинку:
![it52_bug](https://cloud.githubusercontent.com/assets/1313744/16699417/a74e1dae-455c-11e6-884f-7bdcfbfb949a.png)
Firefox 44, Windows 7

**Comment by kugaevsky** [comment]
Жду PR.

**Comment by kugaevsky** [comment]
Поправлено.
