### ISSUE TITLE
Показываются устаревшие события

### ISSUE THREAD

**Issue by noroot** [NNRUG/it52-rails#86]
Скорее всего неправильно выставленный timezone приводит к тому что показываются устаревшие старые события на главной странице.
![image](https://cloud.githubusercontent.com/assets/59066/26473220/e5bda926-41b2-11e7-999a-68cf44658836.png)

**Comment by kugaevsky** [comment]
Это не баг, а фича.

Так как у нас нет времени окончания события, то мы считаем будущими все события, начиная с сегодняшнего дня и далее с дискретностью в одни сутки. То есть сегодняшнее событие будет отображаться до начала следующего дня.

https://github.com/NNRUG/it52-rails/blob/it52/app/models/event.rb#L40

Если думаешь, что логику надо поменять, то на какую?

**Comment by noroot** [comment]
Понял, тогда можно закрыть. Если нет событий на текущий день можно с "отбивкой" показывать 3 последних которые были.

**Comment by kugaevsky** [comment]
Вот тут не уверен. Слишком хитрая логика — можно запутаться.

Мы сейчас показываем заглушку с предложением самим устроить тусу. https://github.com/NNRUG/it52-rails/blob/it52/app/views/events/index.html.slim#L24

Возможно, имеет смысл под заглушкой показывать ссылки на три последних митапа.
