### ISSUE TITLE
ID chat invalid

### ISSUE THREAD

**Issue by jirka66** [NNRUG/it52-rails#90]
#
When i write my chat, chnnel was close and i cant join.

my link
https://web.telegram.org/#/im?p=s1133816709_7775752152870038121

My Error:
Method: channels.getFullChannel
Result: {"_":"rpc_error","error_code":400,"error_message":"CHANNEL_INVALID"}

**Comment by kugaevsky** [comment]
Link to channel — https://t.me/it52info
