### ISSUE TITLE
Invalid Telegram joinlink for pirvate group - help!

### ISSUE THREAD

**Issue by crypwin** [NNRUG/it52-rails#91]
I invited someone to my privategroup but, the guy can't join, he gets an error

Link:
https://t.me/joinchat/Hl0tU0tMlXW69KpkxTmgOA
Error message:
Method: messages.checkChatInvite
Result: {"_":"rpc_error","error_code":400,"error_message":"INVITE_HASH_EXPIRED"}

I have refreshed the link a few times but it doens't seems to  work
Thanks!
Erwin

**Comment by top4ek** [comment]
use `@nnrug` shortcut

**Comment by crypwin** [comment]
Sorry, but I don't understand you answer, can you be more specific?

**Comment by kugaevsky** [comment]
Что за спам говно-айсиошными каналами?

**Comment by top4ek** [comment]
Охтыжёп :)
