### ISSUE TITLE
Github OAuth сломано

### ISSUE THREAD

**Issue by skapral** [NNRUG/it52-rails#93]
### Steps to reproduce:

1. Идем логиниться: https://www.it52.info/login
2. Кликаем на "Войти через GitHub"

### Expected result

OAuth-аутентифиация через гитхаб

### Actual result

```
Ой!
Такой страницы у нас нет.

Вернуться на главную страницу.
```

### Additional info

То же самое происходит, если попробовать связать свой аккаунт в с GitHub на странице https://www.it52.info/my/profile.

**Comment by kugaevsky** [comment]
Спасибо, починили.
