### ISSUE TITLE
Upgrade System in C# (Code help)

### ISSUE THREAD

**Issue by CrossAlex21** [NNRUG/it52-rails#97]
First,im 12 (don't judge),second,i just want to improve my code for a game in unity.
This is my code:
using UnityEngine;
using System.Collections;

public class UpgradeButton : MonoBehaviour {
	//function thingies
	public float coal 0.00f;
	public float cost 100.0f;
	GUIText upgradeText;
	upgradeText enabled = false;
	//animation on startup
	void startupAnim () {
		anim = GetComponent<Animation>();
	}
    //when the game starts
	void Start() {
		public UnityEngine.UI.Text coalDisplay;
		}
	//upgrade functions
	void Update() {
		if (coal < cost) {
			anim.Play("cantUpgrade");
		    }
		if (coal > cost) + if (Input.GetKeyDown("U") do {
			coalDisplay.text = "Metal Mined: " + coal;
				}
	    }
	}
} 
Is it kinda good or very bad? (so i can improve)

**Comment by kugaevsky** [comment]
Hi there.
I believe you missed the repo. This is a web project built with ruby on rails, not C#.
